package com.oai.displaylauncher;

import androidx.annotation.Nullable;

import java.util.ArrayList;
import java.util.List;
import java.util.Locale;

public final class SupportedAliasCatalog {
    private SupportedAliasCatalog() {
    }

    private static final SupportedAliasApp[] VALUES = new SupportedAliasApp[] {
                new SupportedAliasApp("navi", "Яндекс Навигатор",
                        new String[] {"ru.yandex.yandexnavi"},
                        new String[] {"Яндекс Навигатор", "Yandex Навигатор", "Yandex Navigator"},
                        new String[] {"com.oai.displaylauncher.launcher.NaviMainLauncherActivity", "com.oai.displaylauncher.launcher.NaviPassengerLauncherActivity", "com.oai.displaylauncher.launcher.NaviFullLauncherActivity", "com.oai.displaylauncher.launcher.NaviCeilingLauncherActivity"}),
                new SupportedAliasApp("maps", "Яндекс Карты",
                        new String[] {"ru.yandex.yandexmaps"},
                        new String[] {"Яндекс Карты", "Yandex Maps", "Yandex Карты"},
                        new String[] {"com.oai.displaylauncher.launcher.MapsMainLauncherActivity", "com.oai.displaylauncher.launcher.MapsPassengerLauncherActivity", "com.oai.displaylauncher.launcher.MapsFullLauncherActivity", "com.oai.displaylauncher.launcher.MapsCeilingLauncherActivity"}),
                new SupportedAliasApp("youtube", "YouTube",
                        new String[] {"app.morphe.android.youtube", "com.google.android.youtube"},
                        new String[] {"YouTube"},
                        new String[] {"com.oai.displaylauncher.launcher.YouTubeMainLauncherActivity", "com.oai.displaylauncher.launcher.YouTubePassengerLauncherActivity", "com.oai.displaylauncher.launcher.YouTubeFullLauncherActivity", "com.oai.displaylauncher.launcher.YouTubeCeilingLauncherActivity"}),
                new SupportedAliasApp("twogis", "2GIS",
                        new String[] {"ru.dublgis.dgismobile"},
                        new String[] {"2GIS", "2ГИС"},
                        new String[] {"com.oai.displaylauncher.launcher.TwoGisMainLauncherActivity", "com.oai.displaylauncher.launcher.TwoGisPassengerLauncherActivity", "com.oai.displaylauncher.launcher.TwoGisFullLauncherActivity", "com.oai.displaylauncher.launcher.TwoGisCeilingLauncherActivity"}),
                new SupportedAliasApp("app005", "MAPS.ME",
                        new String[] {},
                        new String[] {"MAPS.ME"},
                        new String[] {"com.oai.displaylauncher.launcher.App005MainLauncherActivity", "com.oai.displaylauncher.launcher.App005PassengerLauncherActivity", "com.oai.displaylauncher.launcher.App005FullLauncherActivity", "com.oai.displaylauncher.launcher.App005CeilingLauncherActivity"}),
                new SupportedAliasApp("app006", "Waze",
                        new String[] {"com.waze"},
                        new String[] {"Waze"},
                        new String[] {"com.oai.displaylauncher.launcher.App006MainLauncherActivity", "com.oai.displaylauncher.launcher.App006PassengerLauncherActivity", "com.oai.displaylauncher.launcher.App006FullLauncherActivity", "com.oai.displaylauncher.launcher.App006CeilingLauncherActivity"}),
                new SupportedAliasApp("app007", "Organic Maps",
                        new String[] {"app.organicmaps"},
                        new String[] {"Organic Maps"},
                        new String[] {"com.oai.displaylauncher.launcher.App007MainLauncherActivity", "com.oai.displaylauncher.launcher.App007PassengerLauncherActivity", "com.oai.displaylauncher.launcher.App007FullLauncherActivity", "com.oai.displaylauncher.launcher.App007CeilingLauncherActivity"}),
                new SupportedAliasApp("app008", "CityGuide",
                        new String[] {},
                        new String[] {"CityGuide"},
                        new String[] {"com.oai.displaylauncher.launcher.App008MainLauncherActivity", "com.oai.displaylauncher.launcher.App008PassengerLauncherActivity", "com.oai.displaylauncher.launcher.App008FullLauncherActivity", "com.oai.displaylauncher.launcher.App008CeilingLauncherActivity"}),
                new SupportedAliasApp("app009", "2Chargers",
                        new String[] {},
                        new String[] {"2Chargers"},
                        new String[] {"com.oai.displaylauncher.launcher.App009MainLauncherActivity", "com.oai.displaylauncher.launcher.App009PassengerLauncherActivity", "com.oai.displaylauncher.launcher.App009FullLauncherActivity", "com.oai.displaylauncher.launcher.App009CeilingLauncherActivity"}),
                new SupportedAliasApp("app010", "Brixby - зарядки",
                        new String[] {},
                        new String[] {"Brixby - зарядки", "Brixby"},
                        new String[] {"com.oai.displaylauncher.launcher.App010MainLauncherActivity", "com.oai.displaylauncher.launcher.App010PassengerLauncherActivity", "com.oai.displaylauncher.launcher.App010FullLauncherActivity", "com.oai.displaylauncher.launcher.App010CeilingLauncherActivity"}),
                new SupportedAliasApp("app011", "Malanka NEW",
                        new String[] {},
                        new String[] {"Malanka NEW", "Malanka"},
                        new String[] {"com.oai.displaylauncher.launcher.App011MainLauncherActivity", "com.oai.displaylauncher.launcher.App011PassengerLauncherActivity", "com.oai.displaylauncher.launcher.App011FullLauncherActivity", "com.oai.displaylauncher.launcher.App011CeilingLauncherActivity"}),
                new SupportedAliasApp("app012", "Парковки",
                        new String[] {},
                        new String[] {"Парковки", "Парковки России"},
                        new String[] {"com.oai.displaylauncher.launcher.App012MainLauncherActivity", "com.oai.displaylauncher.launcher.App012PassengerLauncherActivity", "com.oai.displaylauncher.launcher.App012FullLauncherActivity", "com.oai.displaylauncher.launcher.App012CeilingLauncherActivity"}),
                new SupportedAliasApp("app013", "Гор. Парковки",
                        new String[] {},
                        new String[] {"Гор. Парковки", "Гор Парковки"},
                        new String[] {"com.oai.displaylauncher.launcher.App013MainLauncherActivity", "com.oai.displaylauncher.launcher.App013PassengerLauncherActivity", "com.oai.displaylauncher.launcher.App013FullLauncherActivity", "com.oai.displaylauncher.launcher.App013CeilingLauncherActivity"}),
                new SupportedAliasApp("app014", "ContraCam",
                        new String[] {},
                        new String[] {"ContraCam"},
                        new String[] {"com.oai.displaylauncher.launcher.App014MainLauncherActivity", "com.oai.displaylauncher.launcher.App014PassengerLauncherActivity", "com.oai.displaylauncher.launcher.App014FullLauncherActivity", "com.oai.displaylauncher.launcher.App014CeilingLauncherActivity"}),
                new SupportedAliasApp("app015", "Hud Speed",
                        new String[] {},
                        new String[] {"Hud Speed", "HUD Speed"},
                        new String[] {"com.oai.displaylauncher.launcher.App015MainLauncherActivity", "com.oai.displaylauncher.launcher.App015PassengerLauncherActivity", "com.oai.displaylauncher.launcher.App015FullLauncherActivity", "com.oai.displaylauncher.launcher.App015CeilingLauncherActivity"}),
                new SupportedAliasApp("app016", "Real Time GPS Tracker",
                        new String[] {},
                        new String[] {"Real Time GPS Tracker"},
                        new String[] {"com.oai.displaylauncher.launcher.App016MainLauncherActivity", "com.oai.displaylauncher.launcher.App016PassengerLauncherActivity", "com.oai.displaylauncher.launcher.App016FullLauncherActivity", "com.oai.displaylauncher.launcher.App016CeilingLauncherActivity"}),
                new SupportedAliasApp("app017", "Яндекс Путешествия",
                        new String[] {},
                        new String[] {"Яндекс Путешествия", "Yandex Travel", "Yandex Путешествия"},
                        new String[] {"com.oai.displaylauncher.launcher.App017MainLauncherActivity", "com.oai.displaylauncher.launcher.App017PassengerLauncherActivity", "com.oai.displaylauncher.launcher.App017FullLauncherActivity", "com.oai.displaylauncher.launcher.App017CeilingLauncherActivity"}),
                new SupportedAliasApp("app018", "Tripadvisor",
                        new String[] {},
                        new String[] {"Tripadvisor", "TripAdvisor"},
                        new String[] {"com.oai.displaylauncher.launcher.App018MainLauncherActivity", "com.oai.displaylauncher.launcher.App018PassengerLauncherActivity", "com.oai.displaylauncher.launcher.App018FullLauncherActivity", "com.oai.displaylauncher.launcher.App018CeilingLauncherActivity"}),
                new SupportedAliasApp("app019", "AnyApp Keys",
                        new String[] {},
                        new String[] {"AnyApp Keys"},
                        new String[] {"com.oai.displaylauncher.launcher.App019MainLauncherActivity", "com.oai.displaylauncher.launcher.App019PassengerLauncherActivity", "com.oai.displaylauncher.launcher.App019FullLauncherActivity", "com.oai.displaylauncher.launcher.App019CeilingLauncherActivity"}),
                new SupportedAliasApp("app020", "Корзина",
                        new String[] {},
                        new String[] {"Корзина"},
                        new String[] {"com.oai.displaylauncher.launcher.App020MainLauncherActivity", "com.oai.displaylauncher.launcher.App020PassengerLauncherActivity", "com.oai.displaylauncher.launcher.App020FullLauncherActivity", "com.oai.displaylauncher.launcher.App020CeilingLauncherActivity"}),
                new SupportedAliasApp("app021", "Passanger Screen",
                        new String[] {},
                        new String[] {"Passanger Screen", "Passenger Screen"},
                        new String[] {"com.oai.displaylauncher.launcher.App021MainLauncherActivity", "com.oai.displaylauncher.launcher.App021PassengerLauncherActivity", "com.oai.displaylauncher.launcher.App021FullLauncherActivity", "com.oai.displaylauncher.launcher.App021CeilingLauncherActivity"}),
                new SupportedAliasApp("app022", "Microsoft SwiftKey",
                        new String[] {},
                        new String[] {"Microsoft SwiftKey", "SwiftKey"},
                        new String[] {"com.oai.displaylauncher.launcher.App022MainLauncherActivity", "com.oai.displaylauncher.launcher.App022PassengerLauncherActivity", "com.oai.displaylauncher.launcher.App022FullLauncherActivity", "com.oai.displaylauncher.launcher.App022CeilingLauncherActivity"}),
                new SupportedAliasApp("app023", "Yandex Browser",
                        new String[] {"com.yandex.browser"},
                        new String[] {"Yandex Browser", "Яндекс Браузер"},
                        new String[] {"com.oai.displaylauncher.launcher.App023MainLauncherActivity", "com.oai.displaylauncher.launcher.App023PassengerLauncherActivity", "com.oai.displaylauncher.launcher.App023FullLauncherActivity", "com.oai.displaylauncher.launcher.App023CeilingLauncherActivity"}),
                new SupportedAliasApp("app024", "Yandex Browser Lite",
                        new String[] {"com.yandex.browser.lite"},
                        new String[] {"Yandex Browser Lite", "Яндекс Браузер Lite"},
                        new String[] {"com.oai.displaylauncher.launcher.App024MainLauncherActivity", "com.oai.displaylauncher.launcher.App024PassengerLauncherActivity", "com.oai.displaylauncher.launcher.App024FullLauncherActivity", "com.oai.displaylauncher.launcher.App024CeilingLauncherActivity"}),
                new SupportedAliasApp("app025", "LiSWMB",
                        new String[] {},
                        new String[] {"LiSWMB"},
                        new String[] {"com.oai.displaylauncher.launcher.App025MainLauncherActivity", "com.oai.displaylauncher.launcher.App025PassengerLauncherActivity", "com.oai.displaylauncher.launcher.App025FullLauncherActivity", "com.oai.displaylauncher.launcher.App025CeilingLauncherActivity"}),
                new SupportedAliasApp("app026", "Lixiang Tweaks",
                        new String[] {},
                        new String[] {"Lixiang Tweaks"},
                        new String[] {"com.oai.displaylauncher.launcher.App026MainLauncherActivity", "com.oai.displaylauncher.launcher.App026PassengerLauncherActivity", "com.oai.displaylauncher.launcher.App026FullLauncherActivity", "com.oai.displaylauncher.launcher.App026CeilingLauncherActivity"}),
                new SupportedAliasApp("app027", "CARMA",
                        new String[] {},
                        new String[] {"CARMA"},
                        new String[] {"com.oai.displaylauncher.launcher.App027MainLauncherActivity", "com.oai.displaylauncher.launcher.App027PassengerLauncherActivity", "com.oai.displaylauncher.launcher.App027FullLauncherActivity", "com.oai.displaylauncher.launcher.App027CeilingLauncherActivity"}),
                new SupportedAliasApp("app028", "System Settings",
                        new String[] {},
                        new String[] {"System Settings", "Settings"},
                        new String[] {"com.oai.displaylauncher.launcher.App028MainLauncherActivity", "com.oai.displaylauncher.launcher.App028PassengerLauncherActivity", "com.oai.displaylauncher.launcher.App028FullLauncherActivity", "com.oai.displaylauncher.launcher.App028CeilingLauncherActivity"}),
                new SupportedAliasApp("app029", "SpeedTest",
                        new String[] {},
                        new String[] {"SpeedTest", "Speed Test"},
                        new String[] {"com.oai.displaylauncher.launcher.App029MainLauncherActivity", "com.oai.displaylauncher.launcher.App029PassengerLauncherActivity", "com.oai.displaylauncher.launcher.App029FullLauncherActivity", "com.oai.displaylauncher.launcher.App029CeilingLauncherActivity"}),
                new SupportedAliasApp("app030", "GPS Test",
                        new String[] {},
                        new String[] {"GPS Test"},
                        new String[] {"com.oai.displaylauncher.launcher.App030MainLauncherActivity", "com.oai.displaylauncher.launcher.App030PassengerLauncherActivity", "com.oai.displaylauncher.launcher.App030FullLauncherActivity", "com.oai.displaylauncher.launcher.App030CeilingLauncherActivity"}),
                new SupportedAliasApp("app031", "LAAuncher",
                        new String[] {},
                        new String[] {"LAAuncher"},
                        new String[] {"com.oai.displaylauncher.launcher.App031MainLauncherActivity", "com.oai.displaylauncher.launcher.App031PassengerLauncherActivity", "com.oai.displaylauncher.launcher.App031FullLauncherActivity", "com.oai.displaylauncher.launcher.App031CeilingLauncherActivity"}),
                new SupportedAliasApp("app032", "LAAuncher REAR",
                        new String[] {},
                        new String[] {"LAAuncher REAR"},
                        new String[] {"com.oai.displaylauncher.launcher.App032MainLauncherActivity", "com.oai.displaylauncher.launcher.App032PassengerLauncherActivity", "com.oai.displaylauncher.launcher.App032FullLauncherActivity", "com.oai.displaylauncher.launcher.App032CeilingLauncherActivity"}),
                new SupportedAliasApp("app033", "Ян Музыка",
                        new String[] {"ru.yandex.music"},
                        new String[] {"Yandex Music", "Яндекс Музыка", "Ян Музыка"},
                        new String[] {"com.oai.displaylauncher.launcher.App033MainLauncherActivity", "com.oai.displaylauncher.launcher.App033PassengerLauncherActivity", "com.oai.displaylauncher.launcher.App033FullLauncherActivity", "com.oai.displaylauncher.launcher.App033CeilingLauncherActivity"}),
                new SupportedAliasApp("app034", "PCRadio",
                        new String[] {},
                        new String[] {"PCRadio", "PC Radio"},
                        new String[] {"com.oai.displaylauncher.launcher.App034MainLauncherActivity", "com.oai.displaylauncher.launcher.App034PassengerLauncherActivity", "com.oai.displaylauncher.launcher.App034FullLauncherActivity", "com.oai.displaylauncher.launcher.App034CeilingLauncherActivity"}),
                new SupportedAliasApp("app035", "Spotify",
                        new String[] {"com.spotify.music"},
                        new String[] {"Spotify"},
                        new String[] {"com.oai.displaylauncher.launcher.App035MainLauncherActivity", "com.oai.displaylauncher.launcher.App035PassengerLauncherActivity", "com.oai.displaylauncher.launcher.App035FullLauncherActivity", "com.oai.displaylauncher.launcher.App035CeilingLauncherActivity"}),
                new SupportedAliasApp("app036", "Apple Music",
                        new String[] {"com.apple.android.music"},
                        new String[] {"Apple Music"},
                        new String[] {"com.oai.displaylauncher.launcher.App036MainLauncherActivity", "com.oai.displaylauncher.launcher.App036PassengerLauncherActivity", "com.oai.displaylauncher.launcher.App036FullLauncherActivity", "com.oai.displaylauncher.launcher.App036CeilingLauncherActivity"}),
                new SupportedAliasApp("app037", "VK Music",
                        new String[] {},
                        new String[] {"VK Music", "VK Музыка"},
                        new String[] {"com.oai.displaylauncher.launcher.App037MainLauncherActivity", "com.oai.displaylauncher.launcher.App037PassengerLauncherActivity", "com.oai.displaylauncher.launcher.App037FullLauncherActivity", "com.oai.displaylauncher.launcher.App037CeilingLauncherActivity"}),
                new SupportedAliasApp("app038", "Кинопоиск",
                        new String[] {"ru.kinopoisk"},
                        new String[] {"Кинопоиск", "Kinopoisk"},
                        new String[] {"com.oai.displaylauncher.launcher.App038MainLauncherActivity", "com.oai.displaylauncher.launcher.App038PassengerLauncherActivity", "com.oai.displaylauncher.launcher.App038FullLauncherActivity", "com.oai.displaylauncher.launcher.App038CeilingLauncherActivity"}),
                new SupportedAliasApp("app039", "START",
                        new String[] {},
                        new String[] {"START"},
                        new String[] {"com.oai.displaylauncher.launcher.App039MainLauncherActivity", "com.oai.displaylauncher.launcher.App039PassengerLauncherActivity", "com.oai.displaylauncher.launcher.App039FullLauncherActivity", "com.oai.displaylauncher.launcher.App039CeilingLauncherActivity"}),
                new SupportedAliasApp("app040", "RUTUBE",
                        new String[] {"rtb.mobile.android"},
                        new String[] {"RUTUBE", "RuTube"},
                        new String[] {"com.oai.displaylauncher.launcher.App040MainLauncherActivity", "com.oai.displaylauncher.launcher.App040PassengerLauncherActivity", "com.oai.displaylauncher.launcher.App040FullLauncherActivity", "com.oai.displaylauncher.launcher.App040CeilingLauncherActivity"}),
                new SupportedAliasApp("app041", "Premier",
                        new String[] {},
                        new String[] {"Premier"},
                        new String[] {"com.oai.displaylauncher.launcher.App041MainLauncherActivity", "com.oai.displaylauncher.launcher.App041PassengerLauncherActivity", "com.oai.displaylauncher.launcher.App041FullLauncherActivity", "com.oai.displaylauncher.launcher.App041CeilingLauncherActivity"}),
                new SupportedAliasApp("app042", "Okko",
                        new String[] {"ru.more.play"},
                        new String[] {"Okko"},
                        new String[] {"com.oai.displaylauncher.launcher.App042MainLauncherActivity", "com.oai.displaylauncher.launcher.App042PassengerLauncherActivity", "com.oai.displaylauncher.launcher.App042FullLauncherActivity", "com.oai.displaylauncher.launcher.App042CeilingLauncherActivity"}),
                new SupportedAliasApp("app043", "Иви",
                        new String[] {"ru.ivi.client"},
                        new String[] {"Иви", "ivi"},
                        new String[] {"com.oai.displaylauncher.launcher.App043MainLauncherActivity", "com.oai.displaylauncher.launcher.App043PassengerLauncherActivity", "com.oai.displaylauncher.launcher.App043FullLauncherActivity", "com.oai.displaylauncher.launcher.App043CeilingLauncherActivity"}),
                new SupportedAliasApp("app044", "Kinopub",
                        new String[] {},
                        new String[] {"Kinopub"},
                        new String[] {"com.oai.displaylauncher.launcher.App044MainLauncherActivity", "com.oai.displaylauncher.launcher.App044PassengerLauncherActivity", "com.oai.displaylauncher.launcher.App044FullLauncherActivity", "com.oai.displaylauncher.launcher.App044CeilingLauncherActivity"}),
                new SupportedAliasApp("app045", "LAMPA",
                        new String[] {},
                        new String[] {"LAMPA", "Lampa"},
                        new String[] {"com.oai.displaylauncher.launcher.App045MainLauncherActivity", "com.oai.displaylauncher.launcher.App045PassengerLauncherActivity", "com.oai.displaylauncher.launcher.App045FullLauncherActivity", "com.oai.displaylauncher.launcher.App045CeilingLauncherActivity"}),
                new SupportedAliasApp("app046", "NTV PLUS",
                        new String[] {},
                        new String[] {"NTV PLUS", "НТВ ПЛЮС"},
                        new String[] {"com.oai.displaylauncher.launcher.App046MainLauncherActivity", "com.oai.displaylauncher.launcher.App046PassengerLauncherActivity", "com.oai.displaylauncher.launcher.App046FullLauncherActivity", "com.oai.displaylauncher.launcher.App046CeilingLauncherActivity"}),
                new SupportedAliasApp("app047", "Zona",
                        new String[] {},
                        new String[] {"Zona"},
                        new String[] {"com.oai.displaylauncher.launcher.App047MainLauncherActivity", "com.oai.displaylauncher.launcher.App047PassengerLauncherActivity", "com.oai.displaylauncher.launcher.App047FullLauncherActivity", "com.oai.displaylauncher.launcher.App047CeilingLauncherActivity"}),
                new SupportedAliasApp("app048", "Deeplex",
                        new String[] {},
                        new String[] {"Deeplex"},
                        new String[] {"com.oai.displaylauncher.launcher.App048MainLauncherActivity", "com.oai.displaylauncher.launcher.App048PassengerLauncherActivity", "com.oai.displaylauncher.launcher.App048FullLauncherActivity", "com.oai.displaylauncher.launcher.App048CeilingLauncherActivity"}),
                new SupportedAliasApp("app049", "FMPLAY",
                        new String[] {"ru.fmplay"},
                        new String[] {"FMPLAY"},
                        new String[] {"com.oai.displaylauncher.launcher.App049MainLauncherActivity", "com.oai.displaylauncher.launcher.App049PassengerLauncherActivity", "com.oai.displaylauncher.launcher.App049FullLauncherActivity", "com.oai.displaylauncher.launcher.App049CeilingLauncherActivity"}),
                new SupportedAliasApp("app050", "FLEX",
                        new String[] {},
                        new String[] {"FLEX"},
                        new String[] {"com.oai.displaylauncher.launcher.App050MainLauncherActivity", "com.oai.displaylauncher.launcher.App050PassengerLauncherActivity", "com.oai.displaylauncher.launcher.App050FullLauncherActivity", "com.oai.displaylauncher.launcher.App050CeilingLauncherActivity"}),
                new SupportedAliasApp("app051", "Bookmate",
                        new String[] {},
                        new String[] {"Bookmate", "Букмейт", "Букмейт: книги и аудиокниги"},
                        new String[] {"com.oai.displaylauncher.launcher.App051MainLauncherActivity", "com.oai.displaylauncher.launcher.App051PassengerLauncherActivity", "com.oai.displaylauncher.launcher.App051FullLauncherActivity", "com.oai.displaylauncher.launcher.App051CeilingLauncherActivity"}),
                new SupportedAliasApp("app052", "Litres",
                        new String[] {},
                        new String[] {"Litres", "Литрес"},
                        new String[] {"com.oai.displaylauncher.launcher.App052MainLauncherActivity", "com.oai.displaylauncher.launcher.App052PassengerLauncherActivity", "com.oai.displaylauncher.launcher.App052FullLauncherActivity", "com.oai.displaylauncher.launcher.App052CeilingLauncherActivity"}),
                new SupportedAliasApp("app053", "XPlayer",
                        new String[] {},
                        new String[] {"XPlayer"},
                        new String[] {"com.oai.displaylauncher.launcher.App053MainLauncherActivity", "com.oai.displaylauncher.launcher.App053PassengerLauncherActivity", "com.oai.displaylauncher.launcher.App053FullLauncherActivity", "com.oai.displaylauncher.launcher.App053CeilingLauncherActivity"}),
                new SupportedAliasApp("app054", "VLC",
                        new String[] {"org.videolan.vlc"},
                        new String[] {"VLC"},
                        new String[] {"com.oai.displaylauncher.launcher.App054MainLauncherActivity", "com.oai.displaylauncher.launcher.App054PassengerLauncherActivity", "com.oai.displaylauncher.launcher.App054FullLauncherActivity", "com.oai.displaylauncher.launcher.App054CeilingLauncherActivity"}),
                new SupportedAliasApp("app055", "VK Video",
                        new String[] {"com.vk.vkvideo"},
                        new String[] {"VK Video", "VK Видео"},
                        new String[] {"com.oai.displaylauncher.launcher.App055MainLauncherActivity", "com.oai.displaylauncher.launcher.App055PassengerLauncherActivity", "com.oai.displaylauncher.launcher.App055FullLauncherActivity", "com.oai.displaylauncher.launcher.App055CeilingLauncherActivity"}),
                new SupportedAliasApp("app056", "Allplay",
                        new String[] {},
                        new String[] {"Allplay"},
                        new String[] {"com.oai.displaylauncher.launcher.App056MainLauncherActivity", "com.oai.displaylauncher.launcher.App056PassengerLauncherActivity", "com.oai.displaylauncher.launcher.App056FullLauncherActivity", "com.oai.displaylauncher.launcher.App056CeilingLauncherActivity"}),
                new SupportedAliasApp("app057", "YouTube для Детей",
                        new String[] {"com.google.android.apps.youtube.kids"},
                        new String[] {"YouTube для Детей", "YouTube Детям", "YouTube Kids"},
                        new String[] {"com.oai.displaylauncher.launcher.App057MainLauncherActivity", "com.oai.displaylauncher.launcher.App057PassengerLauncherActivity", "com.oai.displaylauncher.launcher.App057FullLauncherActivity", "com.oai.displaylauncher.launcher.App057CeilingLauncherActivity"}),
                new SupportedAliasApp("app058", "VOKINO",
                        new String[] {},
                        new String[] {"VOKINO"},
                        new String[] {"com.oai.displaylauncher.launcher.App058MainLauncherActivity", "com.oai.displaylauncher.launcher.App058PassengerLauncherActivity", "com.oai.displaylauncher.launcher.App058FullLauncherActivity", "com.oai.displaylauncher.launcher.App058CeilingLauncherActivity"}),
                new SupportedAliasApp("app059", "Smart Reading",
                        new String[] {},
                        new String[] {"Smart Reading"},
                        new String[] {"com.oai.displaylauncher.launcher.App059MainLauncherActivity", "com.oai.displaylauncher.launcher.App059PassengerLauncherActivity", "com.oai.displaylauncher.launcher.App059FullLauncherActivity", "com.oai.displaylauncher.launcher.App059CeilingLauncherActivity"}),
                new SupportedAliasApp("app060", "Qobuz Beta",
                        new String[] {},
                        new String[] {"Qobuz Beta", "Qobuz"},
                        new String[] {"com.oai.displaylauncher.launcher.App060MainLauncherActivity", "com.oai.displaylauncher.launcher.App060PassengerLauncherActivity", "com.oai.displaylauncher.launcher.App060FullLauncherActivity", "com.oai.displaylauncher.launcher.App060CeilingLauncherActivity"}),
                new SupportedAliasApp("app061", "Lite HD TV",
                        new String[] {},
                        new String[] {"Lite HD TV"},
                        new String[] {"com.oai.displaylauncher.launcher.App061MainLauncherActivity", "com.oai.displaylauncher.launcher.App061PassengerLauncherActivity", "com.oai.displaylauncher.launcher.App061FullLauncherActivity", "com.oai.displaylauncher.launcher.App061CeilingLauncherActivity"}),
                new SupportedAliasApp("app062", "FILMIX UHD",
                        new String[] {},
                        new String[] {"FILMIX UHD", "Filmix UHD"},
                        new String[] {"com.oai.displaylauncher.launcher.App062MainLauncherActivity", "com.oai.displaylauncher.launcher.App062PassengerLauncherActivity", "com.oai.displaylauncher.launcher.App062FullLauncherActivity", "com.oai.displaylauncher.launcher.App062CeilingLauncherActivity"}),
                new SupportedAliasApp("app063", "Звук",
                        new String[] {"com.zvooq.openplay"},
                        new String[] {"Звук", "Zvuk"},
                        new String[] {"com.oai.displaylauncher.launcher.App063MainLauncherActivity", "com.oai.displaylauncher.launcher.App063PassengerLauncherActivity", "com.oai.displaylauncher.launcher.App063FullLauncherActivity", "com.oai.displaylauncher.launcher.App063CeilingLauncherActivity"}),
                new SupportedAliasApp("app064", "МУЛЬТ",
                        new String[] {},
                        new String[] {"МУЛЬТ", "Мульт"},
                        new String[] {"com.oai.displaylauncher.launcher.App064MainLauncherActivity", "com.oai.displaylauncher.launcher.App064PassengerLauncherActivity", "com.oai.displaylauncher.launcher.App064FullLauncherActivity", "com.oai.displaylauncher.launcher.App064CeilingLauncherActivity"}),
                new SupportedAliasApp("app065", "Лайм HD TV",
                        new String[] {},
                        new String[] {"Лайм HD TV", "Лайм TV"},
                        new String[] {"com.oai.displaylauncher.launcher.App065MainLauncherActivity", "com.oai.displaylauncher.launcher.App065PassengerLauncherActivity", "com.oai.displaylauncher.launcher.App065FullLauncherActivity", "com.oai.displaylauncher.launcher.App065CeilingLauncherActivity"}),
                new SupportedAliasApp("app066", "Wink",
                        new String[] {"ru.rt.video.app.mobile", "ru.rt.video.app.tv"},
                        new String[] {"Wink"},
                        new String[] {"com.oai.displaylauncher.launcher.App066MainLauncherActivity", "com.oai.displaylauncher.launcher.App066PassengerLauncherActivity", "com.oai.displaylauncher.launcher.App066FullLauncherActivity", "com.oai.displaylauncher.launcher.App066CeilingLauncherActivity"}),
                new SupportedAliasApp("app067", "Deezer",
                        new String[] {"deezer.android.app"},
                        new String[] {"Deezer"},
                        new String[] {"com.oai.displaylauncher.launcher.App067MainLauncherActivity", "com.oai.displaylauncher.launcher.App067PassengerLauncherActivity", "com.oai.displaylauncher.launcher.App067FullLauncherActivity", "com.oai.displaylauncher.launcher.App067CeilingLauncherActivity"}),
                new SupportedAliasApp("app068", "KION",
                        new String[] {"ru.mts.mtstv"},
                        new String[] {"KION", "KION – фильмы, сериалы и тв"},
                        new String[] {"com.oai.displaylauncher.launcher.App068MainLauncherActivity", "com.oai.displaylauncher.launcher.App068PassengerLauncherActivity", "com.oai.displaylauncher.launcher.App068FullLauncherActivity", "com.oai.displaylauncher.launcher.App068CeilingLauncherActivity"}),
                new SupportedAliasApp("app069", "OTT-play FOSS",
                        new String[] {},
                        new String[] {"OTT-play FOSS", "OTTPlay", "OTT Play FOSS"},
                        new String[] {"com.oai.displaylauncher.launcher.App069MainLauncherActivity", "com.oai.displaylauncher.launcher.App069PassengerLauncherActivity", "com.oai.displaylauncher.launcher.App069FullLauncherActivity", "com.oai.displaylauncher.launcher.App069CeilingLauncherActivity"}),
                new SupportedAliasApp("app070", "TorrServe",
                        new String[] {},
                        new String[] {"TorrServe"},
                        new String[] {"com.oai.displaylauncher.launcher.App070MainLauncherActivity", "com.oai.displaylauncher.launcher.App070PassengerLauncherActivity", "com.oai.displaylauncher.launcher.App070FullLauncherActivity", "com.oai.displaylauncher.launcher.App070CeilingLauncherActivity"}),
                new SupportedAliasApp("app071", "Все на МАТЧ!",
                        new String[] {},
                        new String[] {"Все на МАТЧ!", "Матч ТВ"},
                        new String[] {"com.oai.displaylauncher.launcher.App071MainLauncherActivity", "com.oai.displaylauncher.launcher.App071PassengerLauncherActivity", "com.oai.displaylauncher.launcher.App071FullLauncherActivity", "com.oai.displaylauncher.launcher.App071CeilingLauncherActivity"}),
                new SupportedAliasApp("app072", "Яндекс Радио",
                        new String[] {"ru.yandex.mobile.fmradio"},
                        new String[] {"Яндекс Радио", "Yandex Radio"},
                        new String[] {"com.oai.displaylauncher.launcher.App072MainLauncherActivity", "com.oai.displaylauncher.launcher.App072PassengerLauncherActivity", "com.oai.displaylauncher.launcher.App072FullLauncherActivity", "com.oai.displaylauncher.launcher.App072CeilingLauncherActivity"}),
                new SupportedAliasApp("app073", "Gyawun Music",
                        new String[] {},
                        new String[] {"Gyawun Music"},
                        new String[] {"com.oai.displaylauncher.launcher.App073MainLauncherActivity", "com.oai.displaylauncher.launcher.App073PassengerLauncherActivity", "com.oai.displaylauncher.launcher.App073FullLauncherActivity", "com.oai.displaylauncher.launcher.App073CeilingLauncherActivity"}),
                new SupportedAliasApp("app074", "RadioRecord",
                        new String[] {},
                        new String[] {"RadioRecord", "Radio Record"},
                        new String[] {"com.oai.displaylauncher.launcher.App074MainLauncherActivity", "com.oai.displaylauncher.launcher.App074PassengerLauncherActivity", "com.oai.displaylauncher.launcher.App074FullLauncherActivity", "com.oai.displaylauncher.launcher.App074CeilingLauncherActivity"}),
                new SupportedAliasApp("app075", "VK Видео AA",
                        new String[] {},
                        new String[] {"VK Видео AA", "VK Video AA"},
                        new String[] {"com.oai.displaylauncher.launcher.App075MainLauncherActivity", "com.oai.displaylauncher.launcher.App075PassengerLauncherActivity", "com.oai.displaylauncher.launcher.App075FullLauncherActivity", "com.oai.displaylauncher.launcher.App075CeilingLauncherActivity"}),
                new SupportedAliasApp("app076", "LazyMedia Deluxe",
                        new String[] {},
                        new String[] {"LazyMedia Deluxe", "Lazy Media Deluxe"},
                        new String[] {"com.oai.displaylauncher.launcher.App076MainLauncherActivity", "com.oai.displaylauncher.launcher.App076PassengerLauncherActivity", "com.oai.displaylauncher.launcher.App076FullLauncherActivity", "com.oai.displaylauncher.launcher.App076CeilingLauncherActivity"}),
                new SupportedAliasApp("app077", "Twitch",
                        new String[] {"tv.twitch.android.app"},
                        new String[] {"Twitch"},
                        new String[] {"com.oai.displaylauncher.launcher.App077MainLauncherActivity", "com.oai.displaylauncher.launcher.App077PassengerLauncherActivity", "com.oai.displaylauncher.launcher.App077FullLauncherActivity", "com.oai.displaylauncher.launcher.App077CeilingLauncherActivity"}),
                new SupportedAliasApp("app078", "iTV",
                        new String[] {},
                        new String[] {"iTV"},
                        new String[] {"com.oai.displaylauncher.launcher.App078MainLauncherActivity", "com.oai.displaylauncher.launcher.App078PassengerLauncherActivity", "com.oai.displaylauncher.launcher.App078FullLauncherActivity", "com.oai.displaylauncher.launcher.App078CeilingLauncherActivity"}),
                new SupportedAliasApp("app079", "OttPlayer",
                        new String[] {},
                        new String[] {"OttPlayer", "OTTPlayer"},
                        new String[] {"com.oai.displaylauncher.launcher.App079MainLauncherActivity", "com.oai.displaylauncher.launcher.App079PassengerLauncherActivity", "com.oai.displaylauncher.launcher.App079FullLauncherActivity", "com.oai.displaylauncher.launcher.App079CeilingLauncherActivity"}),
                new SupportedAliasApp("app080", "GetsTV",
                        new String[] {},
                        new String[] {"GetsTV", "Gets TV"},
                        new String[] {"com.oai.displaylauncher.launcher.App080MainLauncherActivity", "com.oai.displaylauncher.launcher.App080PassengerLauncherActivity", "com.oai.displaylauncher.launcher.App080FullLauncherActivity", "com.oai.displaylauncher.launcher.App080CeilingLauncherActivity"}),
                new SupportedAliasApp("app081", "Audials Play",
                        new String[] {},
                        new String[] {"Audials Play"},
                        new String[] {"com.oai.displaylauncher.launcher.App081MainLauncherActivity", "com.oai.displaylauncher.launcher.App081PassengerLauncherActivity", "com.oai.displaylauncher.launcher.App081FullLauncherActivity", "com.oai.displaylauncher.launcher.App081CeilingLauncherActivity"}),
                new SupportedAliasApp("app082", "Amazon Music",
                        new String[] {"com.amazon.mp3"},
                        new String[] {"Amazon Music"},
                        new String[] {"com.oai.displaylauncher.launcher.App082MainLauncherActivity", "com.oai.displaylauncher.launcher.App082PassengerLauncherActivity", "com.oai.displaylauncher.launcher.App082FullLauncherActivity", "com.oai.displaylauncher.launcher.App082CeilingLauncherActivity"}),
                new SupportedAliasApp("app083", "SoundCloud",
                        new String[] {"com.soundcloud.android"},
                        new String[] {"SoundCloud", "Sound Cloud"},
                        new String[] {"com.oai.displaylauncher.launcher.App083MainLauncherActivity", "com.oai.displaylauncher.launcher.App083PassengerLauncherActivity", "com.oai.displaylauncher.launcher.App083FullLauncherActivity", "com.oai.displaylauncher.launcher.App083CeilingLauncherActivity"}),
                new SupportedAliasApp("app084", "Metrolist",
                        new String[] {},
                        new String[] {"Metrolist"},
                        new String[] {"com.oai.displaylauncher.launcher.App084MainLauncherActivity", "com.oai.displaylauncher.launcher.App084PassengerLauncherActivity", "com.oai.displaylauncher.launcher.App084FullLauncherActivity", "com.oai.displaylauncher.launcher.App084CeilingLauncherActivity"}),
                new SupportedAliasApp("app085", "Angry Birds",
                        new String[] {},
                        new String[] {"Angry Birds"},
                        new String[] {"com.oai.displaylauncher.launcher.App085MainLauncherActivity", "com.oai.displaylauncher.launcher.App085PassengerLauncherActivity", "com.oai.displaylauncher.launcher.App085FullLauncherActivity", "com.oai.displaylauncher.launcher.App085CeilingLauncherActivity"}),
                new SupportedAliasApp("app086", "Chess",
                        new String[] {},
                        new String[] {"Chess"},
                        new String[] {"com.oai.displaylauncher.launcher.App086MainLauncherActivity", "com.oai.displaylauncher.launcher.App086PassengerLauncherActivity", "com.oai.displaylauncher.launcher.App086FullLauncherActivity", "com.oai.displaylauncher.launcher.App086CeilingLauncherActivity"}),
                new SupportedAliasApp("app087", "LiveGames",
                        new String[] {},
                        new String[] {"LiveGames", "Live Games"},
                        new String[] {"com.oai.displaylauncher.launcher.App087MainLauncherActivity", "com.oai.displaylauncher.launcher.App087PassengerLauncherActivity", "com.oai.displaylauncher.launcher.App087FullLauncherActivity", "com.oai.displaylauncher.launcher.App087CeilingLauncherActivity"}),
                new SupportedAliasApp("app088", "Telegram",
                        new String[] {"org.telegram.messenger"},
                        new String[] {"Telegram"},
                        new String[] {"com.oai.displaylauncher.launcher.App088MainLauncherActivity", "com.oai.displaylauncher.launcher.App088PassengerLauncherActivity", "com.oai.displaylauncher.launcher.App088FullLauncherActivity", "com.oai.displaylauncher.launcher.App088CeilingLauncherActivity"}),
                new SupportedAliasApp("app089", "Messages",
                        new String[] {},
                        new String[] {"Messages", "Сообщения"},
                        new String[] {"com.oai.displaylauncher.launcher.App089MainLauncherActivity", "com.oai.displaylauncher.launcher.App089PassengerLauncherActivity", "com.oai.displaylauncher.launcher.App089FullLauncherActivity", "com.oai.displaylauncher.launcher.App089CeilingLauncherActivity"}),
                new SupportedAliasApp("app090", "Yandex Mail",
                        new String[] {"ru.yandex.mail"},
                        new String[] {"Yandex Mail", "Яндекс Почта", "Yandex Почта"},
                        new String[] {"com.oai.displaylauncher.launcher.App090MainLauncherActivity", "com.oai.displaylauncher.launcher.App090PassengerLauncherActivity", "com.oai.displaylauncher.launcher.App090FullLauncherActivity", "com.oai.displaylauncher.launcher.App090CeilingLauncherActivity"}),
                new SupportedAliasApp("app091", "VK AA",
                        new String[] {},
                        new String[] {"VK AA", "ВКонтакте", "VK"},
                        new String[] {"com.oai.displaylauncher.launcher.App091MainLauncherActivity", "com.oai.displaylauncher.launcher.App091PassengerLauncherActivity", "com.oai.displaylauncher.launcher.App091FullLauncherActivity", "com.oai.displaylauncher.launcher.App091CeilingLauncherActivity"}),
                new SupportedAliasApp("app092", "Умный Дом",
                        new String[] {},
                        new String[] {"Умный Дом", "Яндекс Дом"},
                        new String[] {"com.oai.displaylauncher.launcher.App092MainLauncherActivity", "com.oai.displaylauncher.launcher.App092PassengerLauncherActivity", "com.oai.displaylauncher.launcher.App092FullLauncherActivity", "com.oai.displaylauncher.launcher.App092CeilingLauncherActivity"}),
                new SupportedAliasApp("app093", "Home Assistant",
                        new String[] {"io.homeassistant.companion.android"},
                        new String[] {"Home Assistant"},
                        new String[] {"com.oai.displaylauncher.launcher.App093MainLauncherActivity", "com.oai.displaylauncher.launcher.App093PassengerLauncherActivity", "com.oai.displaylauncher.launcher.App093FullLauncherActivity", "com.oai.displaylauncher.launcher.App093CeilingLauncherActivity"}),
                new SupportedAliasApp("app094", "eWeather HD",
                        new String[] {},
                        new String[] {"eWeather HD", "eWeather"},
                        new String[] {"com.oai.displaylauncher.launcher.App094MainLauncherActivity", "com.oai.displaylauncher.launcher.App094PassengerLauncherActivity", "com.oai.displaylauncher.launcher.App094FullLauncherActivity", "com.oai.displaylauncher.launcher.App094CeilingLauncherActivity"}),
                new SupportedAliasApp("app095", "Y.Weather",
                        new String[] {},
                        new String[] {"Y.Weather", "Яндекс Погода", "Yandex Weather"},
                        new String[] {"com.oai.displaylauncher.launcher.App095MainLauncherActivity", "com.oai.displaylauncher.launcher.App095PassengerLauncherActivity", "com.oai.displaylauncher.launcher.App095FullLauncherActivity", "com.oai.displaylauncher.launcher.App095CeilingLauncherActivity"}),
                new SupportedAliasApp("app096", "VEGATEL",
                        new String[] {},
                        new String[] {"VEGATEL"},
                        new String[] {"com.oai.displaylauncher.launcher.App096MainLauncherActivity", "com.oai.displaylauncher.launcher.App096PassengerLauncherActivity", "com.oai.displaylauncher.launcher.App096FullLauncherActivity", "com.oai.displaylauncher.launcher.App096CeilingLauncherActivity"}),
                new SupportedAliasApp("app097", "PalGate",
                        new String[] {},
                        new String[] {"PalGate", "Pal Gate"},
                        new String[] {"com.oai.displaylauncher.launcher.App097MainLauncherActivity", "com.oai.displaylauncher.launcher.App097PassengerLauncherActivity", "com.oai.displaylauncher.launcher.App097FullLauncherActivity", "com.oai.displaylauncher.launcher.App097CeilingLauncherActivity"}),
                new SupportedAliasApp("app098", "RuStore",
                        new String[] {},
                        new String[] {"RuStore", "Ru Store"},
                        new String[] {"com.oai.displaylauncher.launcher.App098MainLauncherActivity", "com.oai.displaylauncher.launcher.App098PassengerLauncherActivity", "com.oai.displaylauncher.launcher.App098FullLauncherActivity", "com.oai.displaylauncher.launcher.App098CeilingLauncherActivity"}),
                new SupportedAliasApp("app099", "Интелпарк",
                        new String[] {},
                        new String[] {"Интелпарк"},
                        new String[] {"com.oai.displaylauncher.launcher.App099MainLauncherActivity", "com.oai.displaylauncher.launcher.App099PassengerLauncherActivity", "com.oai.displaylauncher.launcher.App099FullLauncherActivity", "com.oai.displaylauncher.launcher.App099CeilingLauncherActivity"}),
                new SupportedAliasApp("app100", "ПИК Домофон",
                        new String[] {},
                        new String[] {"ПИК Домофон", "ПИК"},
                        new String[] {"com.oai.displaylauncher.launcher.App100MainLauncherActivity", "com.oai.displaylauncher.launcher.App100PassengerLauncherActivity", "com.oai.displaylauncher.launcher.App100FullLauncherActivity", "com.oai.displaylauncher.launcher.App100CeilingLauncherActivity"}),
                new SupportedAliasApp("app101", "Outline",
                        new String[] {},
                        new String[] {"Outline"},
                        new String[] {"com.oai.displaylauncher.launcher.App101MainLauncherActivity", "com.oai.displaylauncher.launcher.App101PassengerLauncherActivity", "com.oai.displaylauncher.launcher.App101FullLauncherActivity", "com.oai.displaylauncher.launcher.App101CeilingLauncherActivity"}),
                new SupportedAliasApp("app102", "Amnezia",
                        new String[] {},
                        new String[] {"Amnezia"},
                        new String[] {"com.oai.displaylauncher.launcher.App102MainLauncherActivity", "com.oai.displaylauncher.launcher.App102PassengerLauncherActivity", "com.oai.displaylauncher.launcher.App102FullLauncherActivity", "com.oai.displaylauncher.launcher.App102CeilingLauncherActivity"}),
                new SupportedAliasApp("app103", "ByeByeDPI",
                        new String[] {},
                        new String[] {"ByeByeDPI"},
                        new String[] {"com.oai.displaylauncher.launcher.App103MainLauncherActivity", "com.oai.displaylauncher.launcher.App103PassengerLauncherActivity", "com.oai.displaylauncher.launcher.App103FullLauncherActivity", "com.oai.displaylauncher.launcher.App103CeilingLauncherActivity"}),
                new SupportedAliasApp("app104", "v2rayNG",
                        new String[] {},
                        new String[] {"v2rayNG"},
                        new String[] {"com.oai.displaylauncher.launcher.App104MainLauncherActivity", "com.oai.displaylauncher.launcher.App104PassengerLauncherActivity", "com.oai.displaylauncher.launcher.App104FullLauncherActivity", "com.oai.displaylauncher.launcher.App104CeilingLauncherActivity"}),
                new SupportedAliasApp("app105", "SafeShell",
                        new String[] {},
                        new String[] {"SafeShell", "Safe Shell"},
                        new String[] {"com.oai.displaylauncher.launcher.App105MainLauncherActivity", "com.oai.displaylauncher.launcher.App105PassengerLauncherActivity", "com.oai.displaylauncher.launcher.App105FullLauncherActivity", "com.oai.displaylauncher.launcher.App105CeilingLauncherActivity"}),
                new SupportedAliasApp("app106", "AmneziaWG",
                        new String[] {},
                        new String[] {"AmneziaWG"},
                        new String[] {"com.oai.displaylauncher.launcher.App106MainLauncherActivity", "com.oai.displaylauncher.launcher.App106PassengerLauncherActivity", "com.oai.displaylauncher.launcher.App106FullLauncherActivity", "com.oai.displaylauncher.launcher.App106CeilingLauncherActivity"}),
                new SupportedAliasApp("app107", "Дядя Ваня",
                        new String[] {},
                        new String[] {"Дядя Ваня"},
                        new String[] {"com.oai.displaylauncher.launcher.App107MainLauncherActivity", "com.oai.displaylauncher.launcher.App107PassengerLauncherActivity", "com.oai.displaylauncher.launcher.App107FullLauncherActivity", "com.oai.displaylauncher.launcher.App107CeilingLauncherActivity"}),
                new SupportedAliasApp("app108", "HitVPN",
                        new String[] {},
                        new String[] {"HitVPN", "Hit VPN"},
                        new String[] {"com.oai.displaylauncher.launcher.App108MainLauncherActivity", "com.oai.displaylauncher.launcher.App108PassengerLauncherActivity", "com.oai.displaylauncher.launcher.App108FullLauncherActivity", "com.oai.displaylauncher.launcher.App108CeilingLauncherActivity"}),
                new SupportedAliasApp("app109", "Навител Навигатор",
                        new String[] {"ru.navitel"},
                        new String[] {"Навител Навигатор", "Navitel Navigator", "Navitel", "Навител"},
                        new String[] {"com.oai.displaylauncher.launcher.App109MainLauncherActivity", "com.oai.displaylauncher.launcher.App109PassengerLauncherActivity", "com.oai.displaylauncher.launcher.App109FullLauncherActivity", "com.oai.displaylauncher.launcher.App109CeilingLauncherActivity"}),
                new SupportedAliasApp("app110", "Car Scanner ELM OBD2",
                        new String[] {"com.ovz.carscanner"},
                        new String[] {"Car Scanner ELM OBD2", "Car Scanner"},
                        new String[] {"com.oai.displaylauncher.launcher.App110MainLauncherActivity", "com.oai.displaylauncher.launcher.App110PassengerLauncherActivity", "com.oai.displaylauncher.launcher.App110FullLauncherActivity", "com.oai.displaylauncher.launcher.App110CeilingLauncherActivity"}),
                new SupportedAliasApp("app111", "Torque Pro",
                        new String[] {"org.prowl.torque"},
                        new String[] {"Torque Pro", "Torque Pro (OBD 2 & Car)", "Torque Pro (OBD2 / автомобиль)"},
                        new String[] {"com.oai.displaylauncher.launcher.App111MainLauncherActivity", "com.oai.displaylauncher.launcher.App111PassengerLauncherActivity", "com.oai.displaylauncher.launcher.App111FullLauncherActivity", "com.oai.displaylauncher.launcher.App111CeilingLauncherActivity"}),
                new SupportedAliasApp("app112", "Torque Lite",
                        new String[] {"org.prowl.torquefree"},
                        new String[] {"Torque Lite", "Torque Lite (OBD2 & Car)"},
                        new String[] {"com.oai.displaylauncher.launcher.App112MainLauncherActivity", "com.oai.displaylauncher.launcher.App112PassengerLauncherActivity", "com.oai.displaylauncher.launcher.App112FullLauncherActivity", "com.oai.displaylauncher.launcher.App112CeilingLauncherActivity"}),
                new SupportedAliasApp("app113", "AIMP",
                        new String[] {"com.aimp.player"},
                        new String[] {"AIMP"},
                        new String[] {"com.oai.displaylauncher.launcher.App113MainLauncherActivity", "com.oai.displaylauncher.launcher.App113PassengerLauncherActivity", "com.oai.displaylauncher.launcher.App113FullLauncherActivity", "com.oai.displaylauncher.launcher.App113CeilingLauncherActivity"}),
                new SupportedAliasApp("app114", "MX Player",
                        new String[] {"com.mxtech.videoplayer.ad"},
                        new String[] {"MX Player"},
                        new String[] {"com.oai.displaylauncher.launcher.App114MainLauncherActivity", "com.oai.displaylauncher.launcher.App114PassengerLauncherActivity", "com.oai.displaylauncher.launcher.App114FullLauncherActivity", "com.oai.displaylauncher.launcher.App114CeilingLauncherActivity"}),
                new SupportedAliasApp("app115", "CarWebGuru",
                        new String[] {"com.softartstudio.carwebguru"},
                        new String[] {"CarWebGuru Car Launcher", "CarWebGuru Launcher", "CarWebGuru", "CWG"},
                        new String[] {"com.oai.displaylauncher.launcher.App115MainLauncherActivity", "com.oai.displaylauncher.launcher.App115PassengerLauncherActivity", "com.oai.displaylauncher.launcher.App115FullLauncherActivity", "com.oai.displaylauncher.launcher.App115CeilingLauncherActivity"}),
                new SupportedAliasApp("app116", "Car Launcher",
                        new String[] {"com.autolauncher.motorcar.free", "com.autolauncher.motorcar"},
                        new String[] {"Car Launcher", "Car Launcher Pro", "Car Launcher PRO"},
                        new String[] {"com.oai.displaylauncher.launcher.App116MainLauncherActivity", "com.oai.displaylauncher.launcher.App116PassengerLauncherActivity", "com.oai.displaylauncher.launcher.App116FullLauncherActivity", "com.oai.displaylauncher.launcher.App116CeilingLauncherActivity"}),
                new SupportedAliasApp("app117", "AGAMA Car Launcher",
                        new String[] {"altergames.carlauncher"},
                        new String[] {"AGAMA Car Launcher", "AGAMA", "Agama"},
                        new String[] {"com.oai.displaylauncher.launcher.App117MainLauncherActivity", "com.oai.displaylauncher.launcher.App117PassengerLauncherActivity", "com.oai.displaylauncher.launcher.App117FullLauncherActivity", "com.oai.displaylauncher.launcher.App117CeilingLauncherActivity"}),
                new SupportedAliasApp("app118", "Headunit Reloaded",
                        new String[] {"gb.xxy.hr"},
                        new String[] {"Headunit Reloaded Emulator HUR", "Headunit Reloaded", "HUR"},
                        new String[] {"com.oai.displaylauncher.launcher.App118MainLauncherActivity", "com.oai.displaylauncher.launcher.App118PassengerLauncherActivity", "com.oai.displaylauncher.launcher.App118FullLauncherActivity", "com.oai.displaylauncher.launcher.App118CeilingLauncherActivity"}),
                new SupportedAliasApp("app119", "GPS АнтиРадар",
                        new String[] {"air.StrelkaSDFREE", "air.StrelkaSD"},
                        new String[] {"GPS АнтиРадар", "GPS АнтиРадар (радар-детектор)", "GPS AntiRadar", "Антирадар", "Антирадар М", "GPS АнтиРадар PRO"},
                        new String[] {"com.oai.displaylauncher.launcher.App119MainLauncherActivity", "com.oai.displaylauncher.launcher.App119PassengerLauncherActivity", "com.oai.displaylauncher.launcher.App119FullLauncherActivity", "com.oai.displaylauncher.launcher.App119CeilingLauncherActivity"}),
                new SupportedAliasApp("app120", "FCC Car Launcher",
                        new String[] {},
                        new String[] {"FCC Car Launcher", "FCC Car Launcher Free", "FCC"},
                        new String[] {"com.oai.displaylauncher.launcher.App120MainLauncherActivity", "com.oai.displaylauncher.launcher.App120PassengerLauncherActivity", "com.oai.displaylauncher.launcher.App120FullLauncherActivity", "com.oai.displaylauncher.launcher.App120CeilingLauncherActivity"}),
                new SupportedAliasApp("app121", "Crony Auto",
                        new String[] {},
                        new String[] {"Crony Auto", "Crony"},
                        new String[] {"com.oai.displaylauncher.launcher.App121MainLauncherActivity", "com.oai.displaylauncher.launcher.App121PassengerLauncherActivity", "com.oai.displaylauncher.launcher.App121FullLauncherActivity", "com.oai.displaylauncher.launcher.App121CeilingLauncherActivity"}),
                new SupportedAliasApp("app122", "NavRadio+",
                        new String[] {},
                        new String[] {"NavRadio+", "NavRadio Plus", "NavRadio"},
                        new String[] {"com.oai.displaylauncher.launcher.App122MainLauncherActivity", "com.oai.displaylauncher.launcher.App122PassengerLauncherActivity", "com.oai.displaylauncher.launcher.App122FullLauncherActivity", "com.oai.displaylauncher.launcher.App122CeilingLauncherActivity"}),
                new SupportedAliasApp("app123", "CarCar Installer",
                        new String[] {"com.carcarlauncher.installer"},
                        new String[] {"CarCar Installer", "CarCar Launcher"},
                        new String[] {"com.oai.displaylauncher.launcher.App123MainLauncherActivity", "com.oai.displaylauncher.launcher.App123PassengerLauncherActivity", "com.oai.displaylauncher.launcher.App123FullLauncherActivity", "com.oai.displaylauncher.launcher.App123CeilingLauncherActivity"}),
    };

    @Nullable
    public static SupportedAliasApp findForTarget(@Nullable AppTarget target) {
        if (target == null) {
            return null;
        }

        String packageName = target.packageName == null ? "" : target.packageName;
        for (SupportedAliasApp app : VALUES) {
            for (String supportedPackage : app.packageNames) {
                if (supportedPackage.equals(packageName)) {
                    return app;
                }
            }
        }

        String normalizedTitle = normalizeTitle(target.title);
        for (SupportedAliasApp app : VALUES) {
            for (String aliasTitle : app.titleAliases) {
                if (titleMatches(normalizedTitle, normalizeTitle(aliasTitle))) {
                    return app;
                }
            }
        }
        return null;
    }

    public static String[] getAllAliasClassNames() {
        List<String> all = new ArrayList<>();
        for (SupportedAliasApp app : VALUES) {
            for (String alias : app.aliasClassNames) {
                all.add(alias);
            }
        }
        return all.toArray(new String[0]);
    }

    private static boolean titleMatches(String left, String right) {
        if (left.isEmpty() || right.isEmpty()) {
            return false;
        }
        if (left.equals(right)) {
            return true;
        }
        if (left.startsWith(right) || right.startsWith(left)) {
            return Math.min(left.length(), right.length()) >= 4;
        }
        return false;
    }

    private static String normalizeTitle(@Nullable String value) {
        if (value == null) {
            return "";
        }
        return value
                .toLowerCase(Locale.ROOT)
                .replace('ё', 'е')
                .replaceAll("[^a-z0-9а-я]+", "");
    }

    public static final class SupportedAliasApp {
        public final String groupKey;
        public final String appTitle;
        public final String[] packageNames;
        public final String[] titleAliases;
        public final String[] aliasClassNames;

        SupportedAliasApp(String groupKey, String appTitle, String[] packageNames, String[] titleAliases, String[] aliasClassNames) {
            this.groupKey = groupKey;
            this.appTitle = appTitle;
            this.packageNames = packageNames;
            this.titleAliases = titleAliases;
            this.aliasClassNames = aliasClassNames;
        }
    }
}
